export const LOADER_CONSTANTS = {
  LOADER_START_REQUEST: 'LOADER_START_REQUEST',
  LOADER_START_SUCCESS: 'LOADER_START_SUCCESS',
  LOADER_STOP_REQUEST: 'LOADER_STOP_REQUEST',
  LOADER_STOP_SUCCESS: 'LOADER_STOP_SUCCESS',
};
