export const Lang = {
  RegisterForm: {
    name: 'Name',
    nameError: 'Please add a valid name',
    age: 'Age',
    ageError: 'Please add a valid age',
    password: 'Password',
    passwordError: 'Please add a valid password',
    mobile: 'Mobile Phone',
    mobileError: 'Please add a valid mobile phone',
    date: 'Date of Birth',
    dateError: 'Please add a valid date of birth',
    email: 'Email',
    emailError: 'Please add a valid email address',
    address: 'Address',
    addressError: 'Please add a valid address',
    occupation: 'Occupation',
    occupationError: 'Please select a valid occupation',
    expr: 'Experience',
    exprError: 'Please select a valid experience',
    docs: 'Upload Documents',
    docsError: 'Please upload a valid document',
    terms: 'I accept the Terms and Conditions',
    GDPA: 'I accept the Privacy Policy',
    receiveNews: 'I want to receive news',
    send: 'Register',
  },
};
