export const PRODUCTS_CONSTANTS = {
  FETCH_CATEGORIES_REQUEST: 'FETCH_CATEGORIES_REQUEST',
  FETCH_CATEGORIES_SUCCESS: 'FETCH_CATEGORIES_SUCCESS',
  FETCH_CATEGORIES_FAILURE: 'FETCH_CATEGORIES_FAILURE',
  FETCH_PRODUCTS_REQUEST: 'FETCH_PRODUCTS_REQUEST',
  FETCH_PRODUCTS_SUCCESS: 'FETCH_PRODUCTS_SUCCESS',
  FETCH_PRODUCTS_FAILURE: 'FETCH_PRODUCTS_FAILURE',
  FETCH_PRODUCT_DETAILS_REQUEST: 'FETCH_PRODUCT_DETAILS_REQUEST',
  FETCH_PRODUCT_DETAILS_SUCCESS: 'FETCH_PRODUCT_DETAILS_SUCCESS',
  FETCH_PRODUCT_DETAILS_FAILURE: 'FETCH_PRODUCT_DETAILS_FAILURE',
};
