export const USER_CONSTANTS = {
  USER_AUTH_REQUEST: 'USER_AUTH_REQUEST',
  USER_AUTH_SUCCESS: 'USER_AUTH_SUCCESS',
  USER_AUTH_FAILURE: 'USER_AUTH_FAILURE',
  USER_REGISTER_REQUEST: 'USER_REGISTER_REQUEST',
  USER_REGISTER_SUCCESS: 'USER_REGISTER_SUCCESS',
  USER_REGISTER_FAILURE: 'USER_REGISTER_FAILURE',
  GET_LOCATION_REQUEST: 'GET_LOCATION_REQUEST',
  GET_LOCATION_SUCCESS: 'GET_LOCATION_SUCCESS',
  GET_LOCATION_FAILURE: 'GET_LOCATION_FAILURE',
};
